// <auto-generated />
namespace NatterbaseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedfromdatemodifiedtocreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedfromdatemodifiedtocreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201903060830008_changed from datemodified to created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
